default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc 'Runs UI Tests.'
  lane :ui_tests do
    run_tests(scheme: "CurrentLocation", xcargs: "-testPlan=UITest")
  end

end


